Tarea 5
Percy Jacobs

```{r}
library(tidyverse)
library(dplyr)

questions <- read_csv('questions.csv')
answers <- read_csv('answers.csv')
tags <- read_csv('tags.csv')
question_tags <- read_csv('question_tags.csv')
```

1. Left-joining questions and tags
```{r}
questions_with_tags <- questions %>%
  left_join(question_tags, by=c("id"="question_id")) %>%
  left_join(tags, by=c("tag_id"="id")) %>%
  mutate(tag_name=replace_na(tag_name,"only-r"))
questions_with_tags
```

2. Comparing scores across tags
```{r}
questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score=mean(score)) %>%
  arrange(desc(mean_score))
```

3. Finding gaps between questions and answers
```{r}
answers
questions

questions %>%
  inner_join(answers, by=c("id"="question_id"), suffix=c("_question", "_answer")) %>%
  mutate(gap=creation_date_answer-creation_date_question)
```

4. Joining question and answer counts
```{r}
answer_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))
```

```{r}
## 4.2.
question_answer_counts <- questions %>%
  left_join(answer_counts, by=c("id"="question_id")) %>%
  mutate(n=replace_na(n,0))
question_answer_counts
```

5. Joining questions, answers, and tags
```{r}
question_tags %>%
  inner_join(question_answer_counts, by=c("question_id"="id")) %>%
  inner_join(tags, by=c("tag_id"="id"))
```

